print("Here you can play a game called Mad Libs.")
print("So now enter some words.")
color = input("Enter a color: ")
plural_noun = input("Enter a plural noun: ")
celebrity = input("Enter a celebrity: ")
print("")
print("YOUR MAD LIB")
print("Roses are " + color)
print(plural_noun + " are blue")
print("I love " + celebrity)
